server:
  port: ${EXPLR_SERVER_PORT:8081}
  shutdown: graceful

spring:
  main:
    banner-mode: off
    
params:
  folder-home: ${EXPLR_FOLDER_HOME:/home/az}
  thread:
    pool-size: ${EXPLR_THREAD_POOL_SIZE:2}
  file:
    deleted: ${EXPLR_FILE_DELETED:false}
    access-denied: ${EXPLR_FILE_ACCESS_DENIED:true}